### ISSUE TITLE
test.js 断言小概率错误

### ISSUE THREAD

**Issue by aoxiaoqiang** [FE-star/exercise17#51]
![image](https://user-images.githubusercontent.com/17998436/41293733-b6d2d0b0-6e88-11e8-8d5a-cdeb001644b1.png)

同理 

```javascript
ob.sum = 0;
val = Math.random() * 1e9 >> 0;
subject.removeObserver(ob);
assert.ok(subject.observers.count() === 0);
subject.notify(val);
assert.ok(ob.sum !== val);
```
这一段中如果 val 随机到了一个0 就算 removeObserver 和 notify 没有问题，的断言`assert.ok(ob.sum !== val);` 也会失败。

**Comment by Yatoo2018** [comment]
仅仅下面的断言会失败，
let sum = 0;
let val = 0;
sum+=val;
assert.ok(sum === val);
这个断言并不会失败。
